# Generated by Django 2.0.2 on 2019-12-28 13:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z_]*$', 'Only uppercase letters and underscores allowed.')])),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z_]*$', 'Only uppercase letters and underscores allowed.')])),
                ('problem_desc', models.TextField()),
                ('sample_input', models.TextField()),
                ('sample_output', models.TextField()),
                ('input_cases', models.TextField()),
                ('output_cases', models.TextField()),
                ('discussions', models.TextField(blank=True, default=None, null=True)),
                ('difficulty', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('assignment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_App.Assignment')),
            ],
        ),
    ]
