# Generated by Django 2.0.2 on 2019-12-29 21:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_App', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='roll_no',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only digits allowed.')]),
        ),
    ]
