# Generated by Django 2.0.2 on 2020-01-04 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_course_abbreviation'),
        ('my_App', '0004_auto_20191229_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.Course'),
        ),
    ]
