# Generated by Django 2.0.2 on 2020-01-04 22:31

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_App', '0005_assignment_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='code',
            field=models.CharField(default=django.utils.timezone.now, max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z_]*$', 'Only uppercase letters and underscores allowed.')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='code',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z_]*$', 'Only uppercase letters and underscores allowed.')]),
        ),
    ]
