# Generated by Django 2.0.2 on 2020-01-05 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_App', '0006_auto_20200104_2231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='assignment_id',
            new_name='assignment',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='name',
            field=models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[A-Z_]*$', 'Only uppercase letters and underscores allowed.')]),
        ),
    ]
