# Generated by Django 2.0.2 on 2020-01-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_App', '0012_testcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='description',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
